version: "3.8"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code

    ports:
      - "127.0.0.1:8000:8000"
    environment:
      # DATABASE_URL="postgres://username:password@hostname:5432/database"
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    stdin_open: true
    tty: true
    depends_on:
      - db
  # api:
  #   build: ./api
  #   command: python manage.py runserver 0.0.0.0:9009
  #   volumes:
  #     - ./api:/code
  #   ports:
  #     - "9009:9009"
  #   depends_on:
  #     - db

